//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdHocCampaignRunner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CallCampaignsEntities : DbContext
    {
        public CallCampaignsEntities()
            : base("name=CallCampaignsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int archiveAdHocCallList(string campaignName)
        {
            var campaignNameParameter = campaignName != null ?
                new ObjectParameter("campaignName", campaignName) :
                new ObjectParameter("campaignName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("archiveAdHocCallList", campaignNameParameter);
        }
    
        public virtual int createAdHocCallList(string campaignName, Nullable<int> callListSessionId)
        {
            var campaignNameParameter = campaignName != null ?
                new ObjectParameter("campaignName", campaignName) :
                new ObjectParameter("campaignName", typeof(string));
    
            var callListSessionIdParameter = callListSessionId.HasValue ?
                new ObjectParameter("callListSessionId", callListSessionId) :
                new ObjectParameter("callListSessionId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createAdHocCallList", campaignNameParameter, callListSessionIdParameter);
        }
    
        public virtual ObjectResult<getAdHocMostRecentSession_Result> getAdHocMostRecentSession()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAdHocMostRecentSession_Result>("getAdHocMostRecentSession");
        }
    }
}
