//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdHocCampaignRunner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ComplianceEntities : DbContext
    {
        public ComplianceEntities()
            : base("name=ComplianceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdHocLog> AdHocLogs { get; set; }
    
        public virtual int AdHoc_Rollup(Nullable<int> pmdClientId, string flavor)
        {
            var pmdClientIdParameter = pmdClientId.HasValue ?
                new ObjectParameter("pmdClientId", pmdClientId) :
                new ObjectParameter("pmdClientId", typeof(int));
    
            var flavorParameter = flavor != null ?
                new ObjectParameter("flavor", flavor) :
                new ObjectParameter("flavor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdHoc_Rollup", pmdClientIdParameter, flavorParameter);
        }
    
        public virtual int AdHoc_RunCampaign(string campaign, Nullable<bool> isNewCampaignCluster)
        {
            var campaignParameter = campaign != null ?
                new ObjectParameter("campaign", campaign) :
                new ObjectParameter("campaign", typeof(string));
    
            var isNewCampaignClusterParameter = isNewCampaignCluster.HasValue ?
                new ObjectParameter("isNewCampaignCluster", isNewCampaignCluster) :
                new ObjectParameter("isNewCampaignCluster", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdHoc_RunCampaign", campaignParameter, isNewCampaignClusterParameter);
        }
    
        public virtual ObjectResult<GetAdHocLog_Result> GetAdHocLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdHocLog_Result>("GetAdHocLog");
        }
    
        public virtual int AdHocRollupCheck()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AdHocRollupCheck");
        }
    }
}
